services:
  backend:
    build:
      context: .  # Assuming the backend code and Dockerfile are in the root directory
      dockerfile: dockerfile  # Adjust if the Dockerfile is named something else
    ports:
      - "3000:3000"  # Exposing port 3000 from the container to the host
    environment:
      NODE_ENV: production
      PORT: 3000
      # FRONTEND_URL: http://localhost:5173  # URL for the frontend service
      FRONTEND_URL: https://attendancefrontend-hhg8arhxhjbjbmfj.centralindia-01.azurewebsites.net/
      JWT_SECRET: c009f72781d65f4a9fcdaee7c9e721d08ff7c6caea02bf5019db21cea90098a1c274b337a53573e4ec5905227e19e2236af4ae7a83ea47530e3e6deb1f42cf32
      DB_HOST: attendancetracker.cluster-cp04ak2iyggj.eu-north-1.rds.amazonaws.com
      DB_USER: root
      DB_PASSWORD: adymysqlrds
      DB_NAME: attendancetracker
      DB_PORT: 3306
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
